### ISSUE TITLE
"del" key adds characters like ٱ

### ISSUE THREAD

**Issue by D4N13L1980** [K-410/textension#1]
I'm using Blender 2.82 on Ubuntu 18.04

I issued this in K-410/blender-scripts before using the text_insert2.py
Maybe its easier for you to find the problem recording to text_insert2.py

When I want to delete the right side of a line with the "del" key it adds a character that looks like a square "ٱ" instead of deleting the right side.

Example:
cursor = |
I place the cursor between c and d:
abc|def
Result after pressing the del key three times:
abeٱٱٱ|def

**Comment by K-410** [comment]
I'm unable to reproduce. There's nothing in this addon (textension) mapped to the `Delete` key.
Are you using other addons that might interfere?

Try this:
1. Enable debug from the interactive console ``bpy.app.debug_wm = True``
2. Open an info editor
3. Press delete in text editor
4. See which operator is being called.

**Comment by D4N13L1980** [comment]
After pressing the del key:
`bpy.ops.textension.insert(TEXTENSION_OT_insert_internal={"init":True}, TEXT_OT_insert={"text":""}, TEXTENSION_OT_insert_internal={"init":False})`

**Comment by K-410** [comment]
Thanks.

Are you using a non-QWERTY keyboard?

Since I can't reproduce this, I'm going to need you to help me track down the actual key being pressed, so I can add it to the key filtering.
I've attached a modified version of the addon which adds some debug prints. It may tell me something about the character produced when you press delete.

[textension.zip](https://github.com/K-410/textension/files/4268434/textension.zip)

Install it as normally.
When you type in text editor, the console should output some information about the current key pressed. Can you paste the text that comes from pressing the delete key?

**Comment by D4N13L1980** [comment]
Yes^^ I'm using a QWERTZ keybord.
consol output for the del key is:
`UI_menutype_draw: opening menu "TEXT_MT_editor_menus"

init insert
 type: DEL 
 value PRESS 
unicode:  
 ascii:  
 enum: 224 

blender addon Text TEXTINPUT ANY False False False

post insert
 type: DEL 
 value PRESS 
unicode:  
 ascii:  
 enum: 224 

UI_menutype_draw: opening menu "TOPBAR_MT_editor_menus"
`

**Comment by K-410** [comment]
Thanks for testing.
Can you see if this fixes it?

[textension.zip](https://github.com/K-410/textension/files/4269005/textension.zip)

**Comment by D4N13L1980** [comment]
Yeah! It works!

**Comment by D4N13L1980** [comment]
I'm at https://blender.chat/channel/python too. Do you plan to implement the minimap, indentguids and whitespace from code_editor.py too? Nice work!

**Comment by K-410** [comment]
That's good. I'll commit the fix.

The code editor addon will likely remain as a separate addon because of its size.
